external:
  cnb:
    url: https://www.cnb.cz
  currency-api:
    url: https://cdn.jsdelivr.net

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=15m

  security:
    user:
      name: user
      password: 1234

logbook:
  format:
    style: http
  predicate:
    exclude:
      - path: "/v3/api-docs"
      - path: "/v3/api-docs/**"
      - path: "/swagger-ui/**"
