external:
  cnb:
    url: https://www.cnb.cz
  currency-api:
    url: https://cdn.jsdelivr.net

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=15m

logbook:
  format:
    style: http